### ISSUE TITLE
Android build fails with the following task : android:checkDebugDuplicateClasses

### ISSUE THREAD

**Issue by oianmol** [TimOrtel/GRPC-Kotlin-Multiplatform#15]
`> Task :android:checkDebugDuplicateClasses FAILED
Execution failed for task ':android:checkDebugDuplicateClasses'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.CheckDuplicatesRunnable
   > Duplicate class com.google.protobuf.AbstractMessageLite found in modules jetified-protobuf-java-3.21.6 (com.google.protobuf:protobuf-java:3.21.6) and jetified-protobuf-javalite-3.21.1 (com.google.protobuf:protobuf-javalite:3.21.1)
     Duplicate class com.google.protobuf.AbstractMessageLite$Builder found in modules jetified-protobuf-java-3.21.6 (com.google.protobuf:protobuf-java:3.21.6) and jetified-protobuf-javalite-3.21.1 (com.google.protobuf:protobuf-javalite:3.21.1)
     Duplicate class com.google.protobuf.AbstractMessageLite$Builder$LimitedInputStream found in modules jetified-protobuf-java-3.21.6 (com.google.protobuf:protobuf-java:3.21.6) and jetified-protobuf-javalite-3.21.1 (com.google.protobuf:protobuf-javalite:3.21.1)
     Duplicate class com.google.protobuf.AbstractMessageLite$InternalOneOfEnum found in modules jetified-protobuf-java-3.21.6 (com.google.protobuf:protobuf-java:3.21.6) and jetified-protobuf-javalite-3.21.1 (com.google.protobuf:protobuf-javalite:3.21.1)
     Duplicate class com.google.protobuf.AbstractParser found in modules jetified-protobuf-java-3.21.6 (com.google.protobuf:protobuf-java:3.21.6) and jetified-protobuf-javalite-3.21.1 (com.google.protobuf:protobuf-javalite:3.21.1)
     Duplicate class com.google.protobuf.AbstractProtobufList found in modules jetified-protobuf-java-3.21.6 (com.google.protobuf:protobuf-java:3.21.6) and jetified-protobuf-javalite-3.21.1 (com.google.protobuf:protobuf-javalite:3.21.1)
     Duplicate class com.google.protobuf.AllocatedBuffer found in modules jetified-protobuf-java-3.21.6 (com.google.protobuf:protobuf-java:3.21.6) and jetified-protobuf-javalite-3.21.1 (com.google.protobuf:protobuf-javalite:3.21.1)
     Duplicate class com.google.protobuf.AllocatedBuffer$1 found in modules jetified-protobuf-java-3.21.6 (com.google.protobuf:protobuf-java:3.21.6) and jetified-protobuf-javalite-3.21.1 (com.google.protobuf:protobuf-javalite:3.21.1)
     Duplicate class com.google.protobuf.AllocatedBuffer$2 found in modules jetified-protobuf-java-3.21.6 (com.google.protobuf:protobuf-java:3.21.6) and jetified-protobuf-javalite-3.21.1 (com.google.protobuf:protobuf-javalite:3.21.1)
     Duplicate class com.google.protobuf.Android found in modules jetified-protobuf-java-3.21.6 (com.google.protobuf:protobuf-java:3.21.6) and jetified-protobuf-javalite-3.21.1 (com.google.protobuf:protobuf-javalite:3.21.1)
     Duplicate class com.google.protobuf.Any found in modules jetified-protobuf-java-3.21.6 (com.google.protobuf:protobuf-java:3.21.6) and jetified-protobuf-javalite-3.21.1 (com.google.protobuf:protobuf-javalite:3.21.1)
     Duplicate class com.google.protobuf.Any$1 found in modules jetified-protobuf-java-3.21.6 (com.google.protobuf:protobuf-java:3.21.6) and jetified-protobuf-javalite-3.21.1 (com.google.protobuf:protobuf-javalite:3.21.1)
     Duplicate class com.google.protobuf.Any$Builder found in modules jetified-protobuf-java-3.21.6 (com.google.protobuf:protobuf-java:3.21.6) and jetified-protobuf-javalite-3.21.1 (com.google.protobuf:protobuf-javalite:3.21.1)
     Duplicate class com.google.protobuf.AnyKt found in modules jetified-protobuf-kotlin-3.21.6 (com.google.protobuf:protobuf-kotlin:3.21.6) and jetified-protobuf-kotlin-lite-3.20.1 (com.google.protobuf:protobuf-kotlin-lite:3.20.1)
     Duplicate class com.google.protobuf.AnyKt$Dsl found in modules jetified-protobuf-kotlin-3.21.6 (com.google.protobuf:protobuf-kotlin:3.21.6) and jetified-protobuf-kotlin-lite-3.20.1 (com.google.protobuf:protobuf-kotlin-lite:3.20.1)
     Duplicate class com.google.protobuf.AnyKt$Dsl$Companion found in modules jetified-protobuf-kotlin-3.21.6 (com.google.protobuf:protobuf-kotlin:3.21.6) and jetified-protobuf-kotlin-lite-3.20.1 (com.google.protobuf:protobuf-kotlin-lite:3.20.1)
     Duplicate class com.google.protobuf.AnyKtKt found in modules jetified-protobuf-kotlin-3.21.6 (com.google.protobuf:protobuf-kotlin:3.21.6) and jetified-protobuf-kotlin-lite-3.20.1 (com.google.protobuf:protobuf-kotlin-lite:3.20.1)
     Duplicate class com.google.protobuf.AnyOrBuilder found in modules jetified-protobuf-java-3.21.6 (com.google.protobuf:protobuf-java:3.21.6) and jetified-protobuf-javalite-3.21.1 (com.google.protobuf:protobuf-javalite:3.21.1)
     Duplicate class com.google.protobuf.AnyProto found in modules jetified-protobuf-java-3.21.6 (com.google.protobuf:protobuf-java:3.21.6) and jetified-protobuf-javalite-3.21.1 (com.google.protobuf:protobuf-javalite:3.21.1)
     Duplicate class com.google.protobuf.Api found in modules jetified-protobuf-java-3.21.6 (com.google.protobuf:protobuf-java:3.21.6) and jetified-protobuf-javalite-3.21.1 (com.google.protobuf:protobuf-javalite:3.21.1)
     Duplicate class com.google.protobuf.Api$1 found in modules jetified-protobuf-java-3.21.6 (com.google.protobuf:protobuf-java:3.21.6) and jetified-protobuf-javalite-3.21.1 (com.google.protobuf:protobuf-javalite:3.21.1)
     Duplicate class com.google.protobuf.Api$Builder found in modules jetified-protobuf-java-3.21.6 (com.google.protobuf:protobuf-java:3.21.6) and jetified-protobuf-javalite-3.21.1 (com.google.protobuf:protobuf-javalite:3.21.1)
     Duplicate class com.google.protobuf.ApiKt found in modules jetified-protobuf-kotlin-3.21.6 (com.google.protobuf:protobuf-kotlin:3.21.6) and jetified-protobuf-kotlin-lite-3.20.1 (com.google.protobuf:protobuf-kotlin-lite:3.20.1)
     Duplicate class com.google.protobuf.ApiKt$Dsl found in modules jetified-protobuf-kotlin-3.21.6 (com.google.protobuf:protobuf-kotlin:3.21.6) and jetified-protobuf-kotlin-lite-3.20.1 (com.google.protobuf:protobuf-kotlin-lite:3.20.1)
     Duplicate class com.google.protobuf.ApiKt$Dsl$Companion found in modules jetified-protobuf-kotlin-3.21.6 (com.google.protobuf:protobuf-kotlin:3.21.6) and jetified-protobuf-kotlin-lite-3.20.1 (com.google.protobuf:protobuf-kotlin-lite:3.20.1)
     Duplicate class com.google.protobuf.ApiKt$Dsl$MethodsProxy found in modules jetified-protobuf-kotlin-3.21.6 (com.google.protobuf:protobuf-kotlin:3.21.6) and jetified-protobuf-kotlin-lite-3.20.1 (com.google.protobuf:protobuf-kotlin-lite:3.20.1)
     Duplicate class com.google.protobuf.ApiKt$Dsl$MixinsProxy found in modules jetified-protobuf-kotlin-3.21.6 (com.google.protobuf:protobuf-kotlin:3.21.6) and jetified-protobuf-kotlin-lite-3.20.1 (com.google.protobuf:protobuf-kotlin-lite:3.20.1)
     Duplicate class com.google.protobuf.ApiKt$Dsl$OptionsProxy found in modules jetified-protobuf-kotlin-3.21.6 (com.google.protobuf:protobuf-kotlin:3.21.6) and jetified-protobuf-kotlin-lite-3.20.1 (com.google.protobuf:protobuf-kotlin-lite:3.20.1)
     Duplicate class com.google.protobuf.ApiKtKt found in modules jetified-protobuf-kotlin-3.21.6 (com.google.protobuf:protobuf-kotlin:3.21.6) and jetified-protobuf-kotlin-lite-3.20.1 (com.google.protobuf:protobuf-kotlin-lite:3.20.1)
     Duplicate class com.google.protobuf.ApiOrBuilder found in modules jetified-protobuf-java-3.21.6 (com.google.protobuf:protobuf-java:3.21.6) and jetified-protobuf-javalite-3.21.1 (com.google.protobuf:protobuf-javalite:3.21.1)
     Duplicate class com.google.protobuf.ApiProto found in modules jetified-protobuf-java-3.21.6 (com.google.protobuf:protobuf-java:3.21.6) and jetified-protobuf-javalite-3.21.1 (com.google.protobuf:protobuf-javalite:3.21.1)
     Duplicate class com.google.protobuf.ArrayDecoders found in modules jetified-protobuf-java-3.21.6 (com.google.protobuf:protobuf-java:3.21.6) and jetified-protobuf-javalite-3.21.1 (com.google.protobuf:protobuf-javalite:3.21.1)
     Duplicate class com.google.protobuf.ArrayDecoders$1 found in modules jetified-protobuf-java-3.21.6 (com.google.protobuf:protobuf-java:3.21.6) and jetified-protobuf-javalite-3.21.1 (com.google.protobuf:protobuf-javalite:3.21.1)
     Duplicate class com.google.protobuf.ArrayDecoders$Registers found in modules jetified-protobuf-java-3.21.6 (com.google.protobuf:protobuf-java:3.21.6) and jetified-protobuf-javalite-3.21.1 (com.google.protobuf:protobuf-javalite:3.21.1)
     Duplicate class com.google.protobuf.BinaryReader found in modules jetified-protobuf-java-3.21.6 (com.google.protobuf:protobuf-java:3.21.6) and jetified-protobuf-javalite-3.21.1 (com.google.protobuf:protobuf-javalite:3.21.1)
     Duplicate class com.google.protobuf.BinaryReader$1 found in modules jetified-protobuf-java-3.21.6 (com.google.protobuf:protobuf-java:3.21.6) and jetified-protobuf-javalite-3.21.1 (com.google.protobuf:protobuf-javalite:3.21.1)
     Duplicate class com.google.protobuf.BinaryReader$SafeHeapReader found in modules jetified-protobuf-java-3.21.6 (com.google.protobuf:protobuf-java:3.21.6) and jetified-protobuf-javalite-3.21.1 (com.google.protobuf:protobuf-javalite:3.21.1)
     Duplicate class com.google.protobuf.BinaryWriter found in modules jetified-protobuf-java-3.21.6 (com.google.protobuf:protobuf-java:3.21.6) and jetified-protobuf-javalite-3.21.1 (com.google.protobuf:protobuf-javalite:3.21.1)
     Duplicate class com.google.protobuf.BinaryWriter$1 found in modules jetified-protobuf-java-3.21.6 (com.google.protobuf:protobuf-java:3.21.6) and jetified-protobuf-javalite-3.21.1 (com.google.protobuf:protobuf-javalite:3.21.1)
     Duplicate class com.google.protobuf.BinaryWriter$SafeDirectWriter found in modules jetified-protobuf-java-3.21.6 (com.google.protobuf:protobuf-java:3.21.6) and jetified-protobuf-javalite-3.21.1 (com.google.protobuf:protobuf-javalite:3.21.1)
     Duplicate class com.google.protobuf.BinaryWriter$SafeHeapWriter found in modules jetified-protobuf-java-3.21.6 (com.google.protobuf:protobuf-java:3.21.6) and jetified-protobuf-javalite-3.21.1 (com.google.protobuf:protobuf-javalite:3.21.1)
     Duplicate class com.google.protobuf.BinaryWriter$UnsafeDirectWriter found in modules jetified-protobuf-java-3.21.6 (com.google.protobuf:protobuf-java:3.21.6) and jetified-protobuf-javalite-3.21.1 (com.google.protobuf:protobuf-javalite:3.21.1)
     Duplicate class com.google.protobuf.BinaryWriter$UnsafeHeapWriter found in modules jetified-protobuf-java-3.21.6 (com.google.protobuf:protobuf-java:3.21.6) and jetified-protobuf-javalite-3.21.1 (com.google.protobuf:protobuf-javalite:3.21.1)
     Duplicate class com.google.protobuf.BoolValue found in modules jetified-protobuf-java-3.21.6 (com.google.protobuf:protobuf-java:3.21.6) and jetified-protobuf-javalite-3.21.1 (com.google.protobuf:protobuf-javalite:3.21.1)
     Duplicate class com.google.protobuf.BoolValue$1 found in modules jetified-protobuf-java-3.21.6 (com.google.protobuf:protobuf-java:3.21.6) and jetified-protobuf-javalite-3.21.1 (com.google.protobuf:protobuf-javalite:3.21.1)
     Duplicate class com.google.protobuf.BoolValue$Builder found in modules jetified-protobuf-java-3.21.6 (com.google.protobuf:protobuf-java:3.21.6) and jetified-protobuf-javalite-3.21.1 (com.google.protobuf:protobuf-javalite:3.21.1)
     Duplicate class com.google.protobuf.BoolValueKt found in modules jetified-protobuf-kotlin-3.21.6 (com.google.protobuf:protobuf-kotlin:3.21.6) and jetified-protobuf-kotlin-lite-3.20.1 (com.google.protobuf:protobuf-kotlin-lite:3.20.1)
     Duplicate class com.google.protobuf.BoolValueKt$Dsl found in modules jetified-protobuf-kotlin-3.21.6 (com.google.protobuf:protobuf-kotlin:3.21.6) and jetified-protobuf-kotlin-lite-3.20.1 (com.google.protobuf:protobuf-kotlin-lite:3.20.1)
     Duplicate class com.google.protobuf.BoolValueKt$Dsl$Companion found in modules jetified-protobuf-kotlin-3.21.6 (com.google.protobuf:protobuf-kotlin:3.21.6) and jetified-protobuf-kotlin-lite-3.20.1 (com.google.protobuf:protobuf-kotlin-lite:3.20.1)
     Duplicate class com.google.protobuf.BoolValueKtKt found in modules jetified-protobuf-kotlin-3.21.6 (com.google.protobuf:protobuf-kotlin:3.21.6) and jetified-protobuf-kotlin-lite-3.20.1 (com.google.protobuf:protobuf-kotlin-lite:3.20.1)
     Duplicate class com.google.protobuf.BoolValueOrBuilder found in modules jetified-protobuf-java-3.21.6 (com.google.protobuf:protobuf-java:3.21.6) and jetified-protobuf-javalite-3.21.1 (com.google.protobuf:protobuf-javalite:3.21.1)
     Duplicate class com.google.protobuf.BooleanArrayList found in modules jetified-protobuf-java-3.21.6 (com.google.protobuf:protobuf-java:3.21.6) and jetified-protobuf-javalite-3.21.1 (com.google.protobuf:protobuf-javalite:3.21.1)
     Duplicate class com.google.protobuf.BufferAllocator found in modules jetified-protobuf-java-3.21.6 (com.google.protobuf:protobuf-java:3.21.6) and jetified-protobuf-javalite-3.21.1 (com.google.protobuf:protobuf-javalite:3.21.1)
     Duplicate class com.google.protobuf.BufferAllocator$1 found in modules jetified-protobuf-java-3.21.6 (com.google.protobuf:protobuf-java:3.21.6) and jetified-protobuf-javalite-3.21.1 (com.google.protobuf:protobuf-javalite:3.21.1)
     Duplicate class com.google.protobuf.ByteBufferWriter found in modules jetified-protobuf-java-3.21.6 (com.google.protobuf:protobuf-java:3.21.6) and jetified-protobuf-javalite-3.21.1 (com.google.protobuf:protobuf-javalite:3.21.1)
     Duplicate class com.google.protobuf.ByteOutput found in modules jetified-protobuf-java-3.21.6 (com.google.protobuf:protobuf-java:3.21.6) and jetified-protobuf-javalite-3.21.1 (com.google.protobuf:protobuf-javalite:3.21.1)
     Duplicate class com.google.protobuf.ByteString found in modules jetified-protobuf-java-3.21.6 (com.google.protobuf:protobuf-java:3.21.6) and jetified-protobuf-javalite-3.21.1 (com.google.protobuf:protobuf-javalite:3.21.1)
     Duplicate class com.google.protobuf.ByteString$1 found in modules jetified-protobuf-java-3.21.6 (com.google.protobuf:protobuf-java:3.21.6) and jetified-protobuf-javalite-3.21.1 (com.google.protobuf:protobuf-javalite:3.21.1)
     Duplicate class com.google.protobuf.ByteString$2 found in modules jetified-protobuf-java-3.21.6 (com.google.protobuf:protobuf-java:3.21.6) and jetified-protobuf-javalite-3.21.1 (com.google.protobuf:protobuf-javalite:3.21.1)
     Duplicate class com.google.protobuf.ByteString$AbstractByteIterator found in modules jetified-protobuf-java-3.21.6 (com.google.protobuf:protobuf-java:3.21.6) and jetified-protobuf-javalite-3.21.1 (com.google.protobuf:protobuf-javalite:3.21.1)
     Duplicate class com.google.protobuf.ByteString$ArraysByteArrayCopier found in modules jetified-protobuf-java-3.21.6 (com.google.protobuf:protobuf-java:3.21.6) and jetified-protobuf-javalite-3.21.1 (com.google.protobuf:protobuf-javalite:3.21.1)
     Duplicate class com.google.protobuf.ByteString$BoundedByteString found in modules jetified-protobuf-java-3.21.6 (com.google.protobuf:protobuf-java:3.21.6) and jetified-protobuf-javalite-3.21.1 (com.google.protobuf:protobuf-javalite:3.21.1)
     Duplicate class com.google.protobuf.ByteString$ByteArrayCopier found in modules jetified-protobuf-java-3.21.6 (com.google.protobuf:protobuf-java:3.21.6) and jetified-protobuf-javalite-3.21.1 (com.google.protobuf:protobuf-javalite:3.21.1)
     Duplicate class com.google.protobuf.ByteString$ByteIterator found in modules jetified-protobuf-java-3.21.6 (com.google.protobuf:protobuf-java:3.21.6) and jetified-protobuf-javalite-3.21.1 (com.google.protobuf:protobuf-javalite:3.21.1)
     Duplicate class com.google.protobuf.ByteString$CodedBuilder found in modules jetified-protobuf-java-3.21.6 (com.google.protobuf:protobuf-java:3.21.6) and jetified-protobuf-javalite-3.21.1 (com.google.protobuf:protobuf-javalite:3.21.1)
     Duplicate class com.google.protobuf.ByteString$LeafByteString found in modules jetified-protobuf-java-3.21.6 (com.google.protobuf:protobuf-java:3.21.6) and jetified-protobuf-javalite-3.21.1 (com.google.protobuf:protobuf-javalite:3.21.1)
     Duplicate class com.google.protobuf.ByteString$LiteralByteString found in modules jetified-protobuf-java-3.21.6 (com.google.protobuf:protobuf-java:3.21.6) and jetified-protobuf-javalite-3.21.1 (com.google.protobuf:protobuf-javalite:3.21.1)
     Duplicate class com.google.protobuf.ByteString$Output found in modules jetified-protobuf-java-3.21.6 (com.google.protobuf:protobuf-java:3.21.6) and jetified-protobuf-javalite-3.21.1 (com.google.protobuf:protobuf-javalite:3.21.1)
     Duplicate class com.google.protobuf.ByteString$SystemByteArrayCopier found in modules jetified-protobuf-java-3.21.6 (com.google.protobuf:protobuf-java:3.21.6) and jetified-protobuf-javalite-3.21.1 (com.google.protobuf:protobuf-javalite:3.21.1)
     Duplicate class com.google.protobuf.BytesValue found in modules jetified-protobuf-java-3.21.6 (com.google.protobuf:protobuf-java:3.21.6) and jetified-protobuf-javalite-3.21.1 (com.google.protobuf:protobuf-javalite:3.21.1)
     Duplicate class com.google.protobuf.BytesValue$1 found in modules jetified-protobuf-java-3.21.6 (com.google.protobuf:protobuf-java:3.21.6) and jetified-protobuf-javalite-3.21.1 (com.google.protobuf:protobuf-javalite:3.21.1)
     Duplicate class com.google.protobuf.BytesValue$Builder found in modules jetified-protobuf-java-3.21.6 (com.google.protobuf:protobuf-java:3.21.6) and jetified-protobuf-javalite-3.21.1 (com.google.protobuf:protobuf-javalite:3.21.1)
     Duplicate class com.google.protobuf.BytesValueKt found in modules jetified-protobuf-kotlin-3.21.6 (com.google.protobuf:protobuf-kotlin:3.21.6) and jetified-protobuf-kotlin-lite-3.20.1 (com.google.protobuf:protobuf-kotlin-lite:3.20.1)
     Duplicate class com.google.protobuf.BytesValueKt$Dsl found in modules jetified-protobuf-kotlin-3.21.6 (com.google.protobuf:protobuf-kotlin:3.21.6) and jetified-protobuf-kotlin-lite-3.20.1 (com.google.protobuf:protobuf-kotlin-lite:3.20.1)
     Duplicate class com.google.protobuf.BytesValueKt$Dsl$Companion found in modules jetified-protobuf-kotlin-3.21.6 (com.google.protobuf:protobuf-kotlin:3.21.6) and jetified-protobuf-kotlin-lite-3.20.1 (com.google.protobuf:protobuf-kotlin-lite:3.20.1)
     Duplicate class com.google.protobuf.BytesValueKtKt found in modules jetified-protobuf-kotlin-3.21.6 (com.google.protobuf:protobuf-kotlin:3.21.6) and jetified-protobuf-kotlin-lite-3.20.1 (com.google.protobuf:protobuf-kotlin-lite:3.20.1)
     Duplicate class com.google.protobuf.BytesValueOrBuilder found in modules jetified-protobuf-java-3.21.6 (com.google.protobuf:protobuf-java:3.21.6) and jetified-protobuf-javalite-3.21.1 (com.google.protobuf:protobuf-javalite:3.21.1)
     Duplicate class com.google.protobuf.CanIgnoreReturnValue found in modules jetified-protobuf-java-3.21.6 (com.google.protobuf:protobuf-java:3.21.6) and jetified-protobuf-javalite-3.21.1 (com.google.protobuf:protobuf-javalite:3.21.1)
     Duplicate class com.google.protobuf.CheckReturnValue found in modules jetified-protobuf-java-3.21.6 (com.google.protobuf:protobuf-java:3.21.6) and jetified-protobuf-javalite-3.21.1 (com.google.protobuf:protobuf-javalite:3.21.1)
     Duplicate class com.google.protobuf.CodedInputStream found in modules jetified-protobuf-java-3.21.6 (com.google.protobuf:protobuf-java:3.21.6) and jetified-protobuf-javalite-3.21.1 (com.google.protobuf:protobuf-javalite:3.21.1)
     Duplicate class com.google.protobuf.CodedInputStream$1 found in modules jetified-protobuf-java-3.21.6 (com.google.protobuf:protobuf-java:3.21.6) and jetified-protobuf-javalite-3.21.1 (com.google.protobuf:protobuf-javalite:3.21.1)
     Duplicate class com.google.protobuf.CodedInputStream$ArrayDecoder found in modules jetified-protobuf-java-3.21.6 (com.google.protobuf:protobuf-java:3.21.6) and jetified-protobuf-javalite-3.21.1 (com.google.protobuf:protobuf-javalite:3.21.1)
     Duplicate class com.google.protobuf.CodedInputStream$IterableDirectByteBufferDecoder found in modules jetified-protobuf-java-3.21.6 (com.google.protobuf:protobuf-java:3.21.6) and jetified-protobuf-javalite-3.21.1 (com.google.protobuf:protobuf-javalite:3.21.1)
     Duplicate class com.google.protobuf.CodedInputStream$StreamDecoder found in modules jetified-protobuf-java-3.21.6 (com.google.protobuf:protobuf-java:3.21.6) and jetified-protobuf-javalite-3.21.1 (com.google.protobuf:protobuf-javalite:3.21.1)
     Duplicate class com.google.protobuf.CodedInputStream$StreamDecoder$RefillCallback found in modules jetified-protobuf-java-3.21.6 (com.google.protobuf:protobuf-java:3.21.6) and jetified-protobuf-javalite-3.21.1 (com.google.protobuf:protobuf-javalite:3.21.1)
     Duplicate class com.google.protobuf.CodedInputStream$StreamDecoder$SkippedDataSink found in modules jetified-protobuf-java-3.21.6 (com.google.protobuf:protobuf-java:3.21.6) and jetified-protobuf-javalite-3.21.1 (com.google.protobuf:protobuf-javalite:3.21.1)
     Duplicate class com.google.protobuf.CodedInputStream$UnsafeDirectNioDecoder found in modules jetified-protobuf-java-3.21.6 (com.google.protobuf:protobuf-java:3.21.6) and jetified-protobuf-javalite-3.21.1 (com.google.protobuf:protobuf-javalite:3.21.1)
     Duplicate class com.google.protobuf.CodedInputStreamReader found in modules jetified-protobuf-java-3.21.6 (com.google.protobuf:protobuf-java:3.21.6) and jetified-protobuf-javalite-3.21.1 (com.google.protobuf:protobuf-javalite:3.21.1)
     Duplicate class com.google.protobuf.CodedInputStreamReader$1 found in modules jetified-protobuf-java-3.21.6 (com.google.protobuf:protobuf-java:3.21.6) and jetified-protobuf-javalite-3.21.1 (com.google.protobuf:protobuf-javalite:3.21.1)
     Duplicate class com.google.protobuf.CodedOutputStream found in modules jetified-protobuf-java-3.21.6 (com.google.protobuf:protobuf-java:3.21.6) and jetified-protobuf-javalite-3.21.1 (com.google.protobuf:protobuf-javalite:3.21.1)
     Duplicate class com.google.protobuf.CodedOutputStream$1 found in modules jetified-protobuf-java-3.21.6 (com.google.protobuf:protobuf-java:3.21.6) and jetified-protobuf-javalite-3.21.1 (com.google.protobuf:protobuf-javalite:3.21.1)
     Duplicate class com.google.protobuf.CodedOutputStream$AbstractBufferedEncoder found in modules jetified-protobuf-java-3.21.6 (com.google.protobuf:protobuf-java:3.21.6) and jetified-protobuf-javalite-3.21.1 (com.google.protobuf:protobuf-javalite:3.21.1)
     Duplicate class com.google.protobuf.CodedOutputStream$ArrayEncoder found in modules jetified-protobuf-java-3.21.6 (com.google.protobuf:protobuf-java:3.21.6) and jetified-protobuf-javalite-3.21.1 (com.google.protobuf:protobuf-javalite:3.21.1)
     Duplicate class com.google.protobuf.CodedOutputStream$ByteOutputEncoder found in modules jetified-protobuf-java-3.21.6 (com.google.protobuf:protobuf-java:3.21.6) and jetified-protobuf-javalite-3.21.1 (com.google.protobuf:protobuf-javalite:3.21.1)
     Duplicate class com.google.protobuf.CodedOutputStream$HeapNioEncoder found in modules jetified-protobuf-java-3.21.6 (com.google.protobuf:protobuf-java:3.21.6) and jetified-protobuf-javalite-3.21.1 (com.google.protobuf:protobuf-javalite:3.21.1)
     Duplicate class com.google.protobuf.CodedOutputStream$OutOfSpaceException found in modules jetified-protobuf-java-3.21.6 (com.google.protobuf:protobuf-java:3.21.6) and jetified-protobuf-javalite-3.21.1 (com.google.protobuf:protobuf-javalite:3.21.1)
     Duplicate class com.google.protobuf.CodedOutputStream$OutputStreamEncoder found in modules jetified-protobuf-java-3.21.6 (com.google.protobuf:protobuf-java:3.21.6) and jetified-protobuf-javalite-3.21.1 (com.google.protobuf:protobuf-javalite:3.21.1)
     Duplicate class com.google.protobuf.CodedOutputStream$SafeDirectNioEncoder found in modules jetified-protobuf-java-3.21.6 (com.google.protobuf:protobuf-java:3.21.6) and jetified-protobuf-javalite-3.21.1 (com.google.protobuf:protobuf-javalite:3.21.1)
     Duplicate class com.google.protobuf.CodedOutputStream$UnsafeDirectNioEncoder found in modules jetified-protobuf-java-3.21.6 (com.google.protobuf:protobuf-java:3.21.6) and jetified-protobuf-javalite-3.21.1 (com.google.protobuf:protobuf-javalite:3.21.1)
     Duplicate class com.google.protobuf.CodedOutputStreamWriter found in modules jetified-protobuf-java-3.21.6 (com.google.protobuf:protobuf-java:3.21.6) and jetified-protobuf-javalite-3.21.1 (com.google.protobuf:protobuf-javalite:3.21.1)
     Duplicate class com.google.protobuf.CodedOutputStreamWriter$1 found in modules jetified-protobuf-java-3.21.6 (com.google.protobuf:protobuf-java:3.21.6) and jetified-protobuf-javalite-3.21.1 (com.google.protobuf:protobuf-javalite:3.21.1)
     Duplicate class com.google.protobuf.CompileTimeConstant found in modules jetified-protobuf-java-3.21.6 (com.google.protobuf:protobuf-java:3.21.6) and jetified-protobuf-javalite-3.21.1 (com.google.protobuf:protobuf-javalite:3.21.1)
     Duplicate class com.google.protobuf.DoubleArrayList found in modules jetified-protobuf-java-3.21.6 (com.google.protobuf:protobuf-java:3.21.6) and jetified-protobuf-javalite-3.21.1 (com.google.protobuf:protobuf-javalite:3.21.1)
     Duplicate class com.google.protobuf.DoubleValue found in modules jetified-protobuf-java-3.21.6 (com.google.protobuf:protobuf-java:3.21.6) and jetified-protobuf-javalite-3.21.1 (com.google.protobuf:protobuf-javalite:3.21.1)
     Duplicate class com.google.protobuf.DoubleValue$1 found in modules jetified-protobuf-java-3.21.6 (com.google.protobuf:protobuf-java:3.21.6) and jetified-protobuf-javalite-3.21.1 (com.google.protobuf:protobuf-javalite:3.21.1)
     Duplicate class com.google.protobuf.DoubleValue$Builder found in modules jetified-protobuf-java-3.21.6 (com.google.protobuf:protobuf-java:3.21.6) and jetified-protobuf-javalite-3.21.1 (com.google.protobuf:protobuf-javalite:3.21.1)
     Duplicate class com.google.protobuf.DoubleValueKt found in modules jetified-protobuf-kotlin-3.21.6 (com.google.protobuf:protobuf-kotlin:3.21.6) and jetified-protobuf-kotlin-lite-3.20.1 (com.google.protobuf:protobuf-kotlin-lite:3.20.1)
     Duplicate class com.google.protobuf.DoubleValueKt$Dsl found in modules jetified-protobuf-kotlin-3.21.6 (com.google.protobuf:protobuf-kotlin:3.21.6) and jetified-protobuf-kotlin-lite-3.20.1 (com.google.protobuf:protobuf-kotlin-lite:3.20.1)
     Duplicate class com.google.protobuf.DoubleValueKt$Dsl$Companion found in modules jetified-protobuf-kotlin-3.21.6 (com.google.protobuf:protobuf-kotlin:3.21.6) and jetified-protobuf-kotlin-lite-3.20.1 (com.google.protobuf:protobuf-kotlin-lite:3.20.1)
     Duplicate class com.google.protobuf.DoubleValueKtKt found in modules jetified-protobuf-kotlin-3.21.6 (com.google.protobuf:protobuf-kotlin:3.21.6) and jetified-protobuf-kotlin-lite-3.20.1 (com.google.protobuf:protobuf-kotlin-lite:3.20.1)
     Duplicate class com.google.protobuf.DoubleValueOrBuilder found in modules jetified-protobuf-java-3.21.6 (com.google.protobuf:protobuf-java:3.21.6) and jetified-protobuf-javalite-3.21.1 (com.google.protobuf:protobuf-javalite:3.21.1)
     Duplicate class com.google.protobuf.Duration found in modules jetified-protobuf-java-3.21.6 (com.google.protobuf:protobuf-java:3.21.6) and jetified-protobuf-javalite-3.21.1 (com.google.protobuf:protobuf-javalite:3.21.1)
     Duplicate class com.google.protobuf.Duration$1 found in modules jetified-protobuf-java-3.21.6 (com.google.protobuf:protobuf-java:3.21.6) and jetified-protobuf-javalite-3.21.1 (com.google.protobuf:protobuf-javalite:3.21.1)
     Duplicate class com.google.protobuf.Duration$Builder found in modules jetified-protobuf-java-3.21.6 (com.google.protobuf:protobuf-java:3.21.6) and jetified-protobuf-javalite-3.21.1 (com.google.protobuf:protobuf-javalite:3.21.1)
     Duplicate class com.google.protobuf.DurationKt found in modules jetified-protobuf-kotlin-3.21.6 (com.google.protobuf:protobuf-kotlin:3.21.6) and jetified-protobuf-kotlin-lite-3.20.1 (com.google.protobuf:protobuf-kotlin-lite:3.20.1)
     Duplicate class com.google.protobuf.DurationKt$Dsl found in modules jetified-protobuf-kotlin-3.21.6 (com.google.protobuf:protobuf-kotlin:3.21.6) and jetified-protobuf-kotlin-lite-3.20.1 (com.google.protobuf:protobuf-kotlin-lite:3.20.1)

**Comment by TimOrtel** [comment]
This happens when you declare your protobuf/grpc dependencies wrongly. A setup that works can be found [here](https://github.com/TimOrtel/GRPC-Kotlin-Multiplatform/blob/master/grpc-multiplatform-lib/build.gradle.kts#L68).

**Comment by TimOrtel** [comment]
Closing this for now.
