### ISSUE TITLE
Support for Swift Package Manager

### ISSUE THREAD

**Issue by realh** [TimOrtel/GRPC-Kotlin-Multiplatform#16]
Is it possible to set up the iOS dependencies using SPM instead of cocoapods? I don't have much experience of either TBH, but I've found SPM to be less hassle, and it looks like many libraries are migrating to it, including swift-grpc. But maybe that's not practical for you, because you have to use the Objective C implementation instead of Swift?

**Comment by TimOrtel** [comment]
I do not know if this is possible and I do not see a reason to do so. If you find a way nevertheless feel free to share it with us.

**Comment by realh** [comment]
It's just that nothing else in my project needs cocoapods and I've had a bad experience with it in the past with Flutter, so I'm trying to avoid it. Installing SPM dependencies in XCode with no iOS package management in gradle works for me. AIUI, ObjC libraries can be distributed by SPM, but not mixed ObjC and Swift, but it looks like cocoapods is the only option for the upstream ObjC grpc back-end at the moment :-(.
