### ISSUE TITLE
Gradle can not resolve the library (KMM)

### ISSUE THREAD

**Issue by realh** [TimOrtel/GRPC-Kotlin-Multiplatform#17]
I'm trying to set this up in a Kotlin Multiplatform Mobile project, but Gradle won't sync. The error is:
```
Could not determine the dependencies of task ':GCshared:transformIosTestCInteropDependenciesMetadataForIde'.
> Could not resolve all task dependencies for configuration ':GCshared:allSourceSetsRuntimeDependenciesMetadata'.
   > Could not find com.github.TimOrtel.GRPC-Kotlin-Multiplatform:grpc-multiplatform-lib:0.2.1.
     Required by:
         project :GCshared

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```

My top-level build.gradle.kts:
```kotlin
buildscript {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
    }
    dependencies {
        classpath(Deps.kotlinGradlePlugin)
        classpath(Deps.androidBuildTools)
        classpath(kotlin("serialization", version = Deps.kotlinVersion))
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven(url = "https://jitpack.io")
    }
}

tasks.register("clean", Delete::class) {
    delete(rootProject.buildDir)
}
```
I have a Deps.kt file in `buildSrc` including these definitions:
```kotlin
object Deps {
    const val grpcKmpVersion = "0.2.1"
    const val grpcKmp = "io.github.timortel.kotlin-multiplatform-grpc-plugin"
    const val grpcKmpLib =
        "com.github.TimOrtel.GRPC-Kotlin-Multiplatform:grpc-multiplatform-lib:$grpcKmpVersion"
    ...
}
```
build.gradle.kts for my shared module:
```
plugins {
    kotlin("multiplatform")
    kotlin("native.cocoapods")
    id("com.android.library")
    id(Deps.grpcKmp) version Deps.grpcKmpVersion
}

// I've tried with and without this block, it makes no difference
dependencies {
    commonMainApi(Deps.grpcKmpLib)
}

kotlin {
    android()
    iosX64()
    iosArm64()
    iosSimulatorArm64()
    ...
    sourceSets {
        val commonMain by getting  {
            dependencies {
                implementation(kotlin("stdlib-common"))
                api(Deps.grpcKmpLib)
                api(Deps.coroutines)
                api(Deps.kotlinDateTime)
            }
            ...
        }
        ...
   }
   ...
}
```
I've tried including `repositories { maven(url = "https://jitpack.io") }` in all sorts of other contexts, some of which cause additional warnings, but nothing I do fixes that main error.

I don't have this problem when syncing gradle in your example, so there must be some crucial difference between KMP for desktop and web and KMM for Android and iOS, but I can't work out what. Do you know of a working open source KMM project using GRPC-KMP that I can use as a template?

**Comment by TimOrtel** [comment]
You should most likely try to get the library running on the develop branch instead of 0.2.1. Maybe this will fix your issue.

**Comment by realh** [comment]
How do I do that? Change "0.2.1" to "devel" or leave out the version altogether? Should I do the same for the plugins?

**Comment by TimOrtel** [comment]
Clone the library and publish it to maven local. I will soon release 0.3.0 of the library. You could also wait for the next release.

**Comment by realh** [comment]
TBH I don't think there's much point for me to struggle with this any more. It seems like it's the ecosystem's fault, not yours, but even writing my own wrappers for every message class and RPC method would be easier. It's said to be easy to create protoc plugins with protogen, so I'll try generating my wrappers that way.

**Comment by essarn** [comment]
> Clone the library and publish it to maven local. I will soon release 0.3.0 of the library. You could also wait for the next release.

When will the new version be released?

**Comment by TimOrtel** [comment]
Once #13 has been resolved.
